"""Adding versioning

Revision ID: 5ba5bacda7b5
Revises: 274e7233d47b
Create Date: 2025-04-07 19:54:59.236755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ba5bacda7b5'
down_revision: Union[str, None] = '274e7233d47b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_blacklist_token', table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.add_column('template_groups', sa.Column('version_id', sa.Integer(), nullable=False))
    op.drop_constraint('template_groups_profile_id_fkey', 'template_groups', type_='foreignkey')
    op.create_foreign_key(None, 'template_groups', 'template_versions', ['version_id'], ['id'])
    op.drop_column('template_groups', 'profile_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_groups', sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'template_groups', type_='foreignkey')
    op.create_foreign_key('template_groups_profile_id_fkey', 'template_groups', 'profiles', ['profile_id'], ['id'])
    op.drop_column('template_groups', 'version_id')
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='token_blacklist_pkey')
    )
    op.create_index('ix_token_blacklist_token', 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
