"""Adding mapping paths

Revision ID: e6fe96c5e19a
Revises: 63065ad0cfc7
Create Date: 2025-04-07 23:33:55.432005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6fe96c5e19a'
down_revision: Union[str, None] = '63065ad0cfc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_blacklist_token', table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.add_column('template_properties', sa.Column('fhir_mapping', sa.String(), nullable=True))
    op.add_column('template_properties', sa.Column('hl7v2_path', sa.String(), nullable=True))
    op.add_column('template_properties', sa.Column('dicom_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_properties', 'dicom_path')
    op.drop_column('template_properties', 'hl7v2_path')
    op.drop_column('template_properties', 'fhir_mapping')
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='token_blacklist_pkey')
    )
    op.create_index('ix_token_blacklist_token', 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
